site_name: Poradnik biwakowania i wędrowania w terenie
nav:
  - 'index.md'
  - Planowanie: 'Planowanie.md'
  - Przygotowanie: 'Przygotowanie.md'
  - Wędrowanie: 'Wedrowanie.md'
  - Podsumowanie: 'Podsumowanie.md'
theme:
  name: material
  features:
    - navigation.instant
  font:
    text: Poppins
  language: pl
  icon:
    #logo: material/nature
    #logo: fas/solid/tree
    logo: fontawesome/solid/tree
  palette:
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/eye
        name: Switch to light mode
          #primary: green
          #accent: light green
  plugins:
    - search:
        lang: en
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
extra_css:
    # - /stylesheets/new.css
  - /stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-1NCLEFZMCY
  
